/*
 * Swagger Petstore
 *
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PetAllOf {
    #[serde(rename = "id")]
    pub id: i64,
}

impl PetAllOf {
    pub fn new(id: i64) -> PetAllOf {
        PetAllOf {
            id,
        }
    }
}


