"""
    Swagger Petstore

    A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Swagger Petstore",
    author="Swagger API Team",
    author_email="apiteam@swagger.io",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Swagger Petstore"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
    A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification  # noqa: E501
    """
)
