"""
    Swagger Petstore

    A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.new_pet import NewPet


class TestNewPet(unittest.TestCase):
    """NewPet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewPet(self):
        """Test NewPet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NewPet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
