/**
 * Swagger Petstore
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NewPet from './NewPet';
import PetAllOf from './PetAllOf';

/**
 * The Pet model module.
 * @module model/Pet
 * @version 1.0.0
 */
class Pet {
    /**
     * Constructs a new <code>Pet</code>.
     * @alias module:model/Pet
     * @implements module:model/NewPet
     * @implements module:model/PetAllOf
     * @param name {String} 
     * @param id {Number} 
     */
    constructor(name, id) { 
        NewPet.initialize(this, name);PetAllOf.initialize(this, id);
        Pet.initialize(this, name, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, id) { 
        obj['name'] = name;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Pet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Pet} obj Optional instance to populate.
     * @return {module:model/Pet} The populated <code>Pet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pet();
            NewPet.constructFromObject(data, obj);
            PetAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Pet.prototype['name'] = undefined;

/**
 * @member {String} tag
 */
Pet.prototype['tag'] = undefined;

/**
 * @member {Number} id
 */
Pet.prototype['id'] = undefined;


// Implement NewPet interface:
/**
 * @member {String} name
 */
NewPet.prototype['name'] = undefined;
/**
 * @member {String} tag
 */
NewPet.prototype['tag'] = undefined;
// Implement PetAllOf interface:
/**
 * @member {Number} id
 */
PetAllOf.prototype['id'] = undefined;




export default Pet;

